### ISSUE TITLE
Add roguelikes et al.

### ISSUE THREAD

**Issue by ffaf1** [bobeff/open-source-games#10]
A handful of suggestions:
- Add a roguelike/roguelite category.
- Add [nethack](http://nethack.org/common/index.html) (needs no reason, one of the most popular and oldest open source games).
- Add [Meritous](http://asceai.net/meritous/) (modern take on the dungeon crawl.
- Add [LibregameWiki](https://libregamewiki.org/Main_Page) to the lists.

**Comment by bobeff** [comment]
10x for your contributions. I added them.
