### ISSUE TITLE
Suggestion: openarena

### ISSUE THREAD

**Issue by kapouer** [bobeff/open-source-games#13]
Obisouly

**Comment by bobeff** [comment]
@kapouer I already included the code of the Quake III Arena in the list. How different is the OpenArena?

**Comment by kapouer** [comment]
Good question, https://github.com/ioquake/ioq3 is actually maintained, whereas https://github.com/id-Software/Quake-III-Arena is currently unusable on a modern computer.

**Comment by bobeff** [comment]
I'm closing this. It is not practical to include all source ports of the ID games. I prefer the original code in the list even though it is not working on modern machines.
