### ISSUE TITLE
Suggestion: Oolite

### ISSUE THREAD

**Issue by Andrew-Cottrell** [bobeff/open-source-games#2]
Oolite game and source code are freely available under the GNU General Public License.

http://www.oolite.org/

> Oolite is inspired by the 8-bit classic Elite, and many aspects of gameplay will be familiar to players of that game. In the tradition of open-world games, there's no overall story: you can be a millionaire trader, a veteran combateer, a feared pirate, a lonely miner, a notorious smuggler, or all of them, or something else entirely, based on your own actions.

https://github.com/OoliteProject/oolite

> Oolite for all platforms [Windows, Linux, OSX] can be built from this repository.

---
Other potential ideas can be found at https://forum.openmw.org/viewtopic.php?p=57882#p57882 and https://osgameclones.com/.

**Comment by bobeff** [comment]
Added,
