### ISSUE TITLE
Solarus game engine

### ISSUE THREAD

**Issue by eleriaqueen** [bobeff/open-source-games#20]
Hello, if gitlab-hosted sourcecode is okay you could add [Solarus Game Engine](https://www.solarus-games.org/) - [Code](https://www.gitlab.com/solarus-games)
It is a game engine that specialises in top-down action-adventure games like Zelda - A Link to the Past.

**Comment by bobeff** [comment]
I added it to another list with [game engines](https://github.com/bobeff/open-source-engines).
