### ISSUE TITLE
The Touhou PC-98 Restoration Project - "ReC98"

### ISSUE THREAD

**Issue by eleriaqueen** [bobeff/open-source-games#26]
ReC98 - [Code](https://github.com/nmlgc/ReC98)

"This project aims to perfectly reconstruct the source code of the first five [Touhou Project](http://en.wikipedia.org/wiki/Touhou_Project) games by ZUN Soft (now Team Shanghai Alice), which were originally released exclusively for the NEC PC-9801 system."

**Comment by bobeff** [comment]
This project has a nighter official site, nighter some screenshots on the GitHub page. I will not add it, because it is hard to determine what exactly I'm adding.
