### ISSUE TITLE
SGDK - Sega Genesis Development Kit

### ISSUE THREAD

**Issue by eleriaqueen** [bobeff/open-source-games#27]
Hey, not sure if adding Open Source development kits for console games to the list is in the scope of this project.

SGDK - [Code](https://github.com/Stephane-D/SGDK)

"SGDK is a free development kit allowing development of software in C language for the Sega Mega Drive."

**Comment by bobeff** [comment]
This is not a game so I added it to another list with [game engines](https://github.com/bobeff/open-source-engines).
