### ISSUE TITLE
Free Hero Mesh

### ISSUE THREAD

**Issue by zzo38** [bobeff/open-source-games#6]
Here is another puzzle game engine (it started as a re-implementation of Everett Kaser's MESH:Hero Hearts game, and can be used with the original game files, but also is many added and improved features and can make up your own games even if you do not have the original game files). I don't know, if you are interest in this kind of puzzle games, but if you are interested, then here it is, in the format that you have specified:

**[Free Hero Mesh](http://zzo38computer.org/freeheromesh)** - Puzzle game engine like Hero Hearts. [[source]](https://chiselapp.com/user/zzo38/repository/freeheromesh)

**Comment by bobeff** [comment]
This engine looks strange to me. There are no screenshots of games using it. This is a list dedicated to open-source games that are playable. I cannot include every random engine on the internet. It will take me too much time to verify that it is really the thing that is stated. Sorry, but I cannot include this.
